
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Button OpenFile;
	
	private global::Gtk.Button URL;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Entry ModDescriptionField;
	
	private global::Gtk.Label ModDescriptionLabel;
	
	private global::Gtk.Entry ModNameField;
	
	private global::Gtk.Label ModNameLabel;
	
	private global::Gtk.Entry SteamNameField1;
	
	private global::Gtk.Label SteamNameLabel;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Label XMLLabel;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView XMLTextView;
	
	private global::Gtk.HButtonBox hbuttonbox3;
	
	private global::Gtk.Button ExportButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.OpenFile = new global::Gtk.Button ();
		this.OpenFile.CanFocus = true;
		this.OpenFile.Name = "OpenFile";
		this.OpenFile.UseUnderline = true;
		this.OpenFile.Label = global::Mono.Unix.Catalog.GetString ("Open XML");
		global::Gtk.Image w1 = new global::Gtk.Image ();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
		this.OpenFile.Image = w1;
		this.hbox3.Add (this.OpenFile);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.OpenFile]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.URL = new global::Gtk.Button ();
		this.URL.CanFocus = true;
		this.URL.Name = "URL";
		this.URL.Label = global::Mono.Unix.Catalog.GetString ("https://github.com/CWMlolzlz/Challenges");
		this.hbox3.Add (this.URL);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.URL]));
		w3.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.ModDescriptionField = new global::Gtk.Entry ();
		this.ModDescriptionField.CanFocus = true;
		this.ModDescriptionField.Name = "ModDescriptionField";
		this.ModDescriptionField.IsEditable = true;
		this.ModDescriptionField.InvisibleChar = '●';
		this.table1.Add (this.ModDescriptionField);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.ModDescriptionField]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ModDescriptionLabel = new global::Gtk.Label ();
		this.ModDescriptionLabel.Name = "ModDescriptionLabel";
		this.ModDescriptionLabel.Xalign = 0F;
		this.ModDescriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Mod Description");
		this.table1.Add (this.ModDescriptionLabel);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.ModDescriptionLabel]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ModNameField = new global::Gtk.Entry ();
		this.ModNameField.CanFocus = true;
		this.ModNameField.Name = "ModNameField";
		this.ModNameField.IsEditable = true;
		this.ModNameField.InvisibleChar = '●';
		this.table1.Add (this.ModNameField);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.ModNameField]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ModNameLabel = new global::Gtk.Label ();
		this.ModNameLabel.Name = "ModNameLabel";
		this.ModNameLabel.Xalign = 0F;
		this.ModNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Mod Name");
		this.table1.Add (this.ModNameLabel);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.ModNameLabel]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.SteamNameField1 = new global::Gtk.Entry ();
		this.SteamNameField1.CanFocus = true;
		this.SteamNameField1.Name = "SteamNameField1";
		this.SteamNameField1.IsEditable = true;
		this.SteamNameField1.InvisibleChar = '●';
		this.table1.Add (this.SteamNameField1);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.SteamNameField1]));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.SteamNameLabel = new global::Gtk.Label ();
		this.SteamNameLabel.Name = "SteamNameLabel";
		this.SteamNameLabel.Xalign = 0F;
		this.SteamNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Steam Name");
		this.table1.Add (this.SteamNameLabel);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.SteamNameLabel]));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.XMLLabel = new global::Gtk.Label ();
		this.XMLLabel.Name = "XMLLabel";
		this.XMLLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("XML File:");
		this.vbox1.Add (this.XMLLabel);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.XMLLabel]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.XMLTextView = new global::Gtk.TextView ();
		this.XMLTextView.CanFocus = true;
		this.XMLTextView.Name = "XMLTextView";
		this.XMLTextView.Editable = false;
		this.GtkScrolledWindow.Add (this.XMLTextView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w15.Position = 4;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox ();
		this.hbuttonbox3.Name = "hbuttonbox3";
		this.vbox1.Add (this.hbuttonbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox3]));
		w16.Position = 5;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.ExportButton = new global::Gtk.Button ();
		this.ExportButton.CanFocus = true;
		this.ExportButton.Name = "ExportButton";
		this.ExportButton.UseUnderline = true;
		this.ExportButton.Label = global::Mono.Unix.Catalog.GetString ("Export");
		this.vbox1.Add (this.ExportButton);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ExportButton]));
		w17.Position = 6;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 478;
		this.DefaultHeight = 438;
		this.SteamNameField1.Hide ();
		this.SteamNameLabel.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenFile.Clicked += new global::System.EventHandler (this.OnOpenFile);
		this.ExportButton.Clicked += new global::System.EventHandler (this.OnExport);
	}
}
